# Generated by Django 4.2.7 on 2026-10-03 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True, verbose_name='会话ID')),
                ('title', models.CharField(default='新会话', max_length=200, verbose_name='会话标题')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Agent会话',
                'verbose_name_plural': 'Agent会话',
                'db_table': 'agent_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('tool', '工具'), ('system', '系统')], max_length=20, verbose_name='角色')),
                ('msg_type', models.CharField(choices=[('text', '文本'), ('tool_call', '工具调用'), ('tool_result', '工具结果'), ('error', '错误'), ('thinking', '思考')], default='text', max_length=20, verbose_name='消息类型')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('tool_name', models.CharField(blank=True, max_length=100, verbose_name='工具名称')),
                ('tool_params', models.JSONField(blank=True, default=dict, verbose_name='工具参数')),
                ('tool_result', models.JSONField(blank=True, default=dict, verbose_name='工具结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.agentsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': 'Agent消息',
                'verbose_name_plural': 'Agent消息',
                'db_table': 'agent_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
