# Generated by Django 4.2.7 on 2026-10-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiproject',
            name='project_type',
            field=models.CharField(choices=[('HTTP', 'HTTP')], max_length=20, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='request_type',
            field=models.CharField(choices=[('HTTP', 'HTTP')], default='HTTP', max_length=20, verbose_name='请求类型'),
        ),
    ]
